global:
  domain: "cx498.coralogix.com"
  clusterName: "ian-bowers-eks-us-east-2"

opentelemetry-agent:
  extraConfig:
    processors:
      filter/single-namespace:
        logs:
          log_record:
            - 'resource.attributes["k8s.namespace.name"] != "default"'
        metrics:
          metric:
            - 'resource.attributes["k8s.namespace.name"] != "default"'
        traces:
          span:
            - 'resource.attributes["k8s.namespace.name"] != "default"'
    service:
      pipelines:
        logs:
          processors:
            - filter/single-namespace
        metrics:
          processors:
            - filter/single-namespace
        traces:
          processors:
            - filter/single-namespace

opentelemetry-cluster-collector:
  extraConfig:
    processors:
      filter/single-namespace:
        logs:
          log_record:
            - 'resource.attributes["k8s.namespace.name"] != "default"'
        metrics:
          metric:
            - 'resource.attributes["k8s.namespace.name"] != "default"'
    service:
      pipelines:
        logs:
          processors:
            - filter/single-namespace
        metrics:
          processors:
            - filter/single-namespace
