apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-3bp
  labels:
    app: checkout-3bp
    service: checkout-3bp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout-3bp
  template:
    metadata:
      labels:
        app: checkout-3bp
        service: checkout-3bp
    spec:
      containers:
      - name: checkout-3bp
        image: public.ecr.aws/w3s4j9x9/ianbowers/ebpf-test-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: SERVICE_NAME
          value: "checkout-3bp"
        - name: SERVER_PORT
          value: "8080"
        - name: NEXT_SERVICE_URL
          value: "http://payment-3bp:8080"
        - name: IS_LEAF_SERVICE
          value: "false"
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms256m"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-3bp
  labels:
    app: checkout-3bp
spec:
  selector:
    app: checkout-3bp
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP 